# Generated by Django 4.2.4 on 2023-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
