# Generated by Django 4.2.4 on 2023-09-06 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_tarea_asignado_a_alter_tarea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
