# Generated by Django 4.2.4 on 2023-09-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_tarea_asignado_por_alter_tarea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('prioridad_alta', 'Prioridad Alta'), ('prioridad_media', 'Prioridad Media'), ('baja_prioridad', 'Prioridad Baja')], default='prioridad_media', max_length=20),
        ),
    ]
